### ISSUE TITLE
这个插件按照说明，没有运行起来

### ISSUE THREAD

**Issue by andfly** [jpush/jpush-react-plugin#1]
这个插件按照说明，没有运行起来，整个Android的目录结构和官方例子不同的地方太多，上手有点难。希望能跟官方例子的目录结构保持一致，并给出详细的说明，谢谢。

**Comment by KenChoi1992** [comment]
我提交了最新代码，把react-native这个文件夹放在外面了，Android 的话应该没问题了，你再看看
