### ISSUE TITLE
安卓编译错误

### ISSUE THREAD

**Issue by jerry81333** [jpush/jpush-react-plugin#12]
为什么安卓照着文档配置后，StopPush，ResumePush都提示Success，但是GetRegistrationID找不到，并且调试时返回-996错误，但是设备是联网的，并且核对了包名申请的APPKey应该没错。

**Comment by KenChoi1992** [comment]
@jerry81333 可以收到推送吗？要记得先调 initPush()

**Comment by jerry81333** [comment]
不好意思，上次没说清楚，是虚拟机跑可以推送，但是真机-996、、、不知道具体是哪里出了问题、、、

**Comment by KenChoi1992** [comment]
@jerry81333 方便发一下日志吗

**Comment by jerry81333** [comment]
index.android.bundle:25276Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components). Check the render method of `Navigator`.
index.android.bundle:25261Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of `Navigator`.
这两条是点击设置的错误日志。
点击其余的并没有什么错误日志，我的测试机是华为，没解锁码没法使用ADB调试；同事手机错误反馈是-996。并且NetInfo反馈是联网状态。
另外getRegistrationID为空。
APPKEY也再次确认过了，没理解错的话，应该是android/app/build.gradle;里的applicationId是吧。
麻烦你了。

**Comment by KenChoi1992** [comment]
你应该是没有正确配置好。正确配置的话可以拿到 RegistrationID（在 initPush()执行后）。另外你这个 undefined 错误就是在 index.js 里面或者你定义 Navigator 的类，比如我们的 demo 提供的 index.android.js，你要跳转的类没有定义。参考一下我们的代码：
```
renderScene(router, navigator) {
    var Component = null;
    this.navigator = navigator;
    switch(router.name) {
      case "pushActivity":
        Component = PushActivity;
        break;
      case "setActivity":
        Component = SetActivity;
        break;
    }

    return <Component navigator = { navigator } />
  }
```
看一下相关的类是不是没有 import 进来

**Comment by KenChoi1992** [comment]
@jerry81333 没有问题的话，我就关闭这个 issue 了。
