### ISSUE TITLE
怎么判断是点击通知方式进入的的还是点击应用图标方式进入应用的

### ISSUE THREAD

**Issue by HouseShine** [jpush/jpush-react-plugin#13]
在杀死应用进程后，当再次打开应用时，怎么判断是点击通知方式进入的的还是点击应用图标方式进入的，JS中有没有什么参数或方法可以判断的

**Comment by huangminlinux** [comment]
你的是， android  还是iOS？

**Comment by HouseShine** [comment]
@huangminlinux js中代码怎么写，有没有相应参数可以调用  Android和iOS两个版本都有

**Comment by KenChoi1992** [comment]
@HouseShine Android 有一个回调：addReceiveOpenNotificationListener()，可以参考 react-native-android 目录下的 push_activity.js 里面的 componentDidMount()方法

**Comment by HouseShine** [comment]
@huangminlinux 这个方法在iOS同样能用吗？ 还是说iOS需要自己架桥实现

**Comment by huangminlinux** [comment]
iOS，现在没有提供这个功能，需要自己桥接

**Comment by HouseShine** [comment]
@huangminlinux @KenChoi1992  十分感谢你们的答复
