### ISSUE TITLE
当app在前台运行时收到推送通知，应该监听哪个事件来处理？

### ISSUE THREAD

**Issue by viix** [jpush/jpush-react-plugin#14]

**Comment by ljspace** [comment]
@viix  可以参考示例代码

`componentDidMount ` 注册事件监听
`componentWillUnmount `移除事件监听

https://github.com/jpush/jpush-react-plugin/blob/master/react-native-android/push_activity.js

**Comment by KenChoi1992** [comment]
@ljspace 给这位仁兄点个赞！

**Comment by Florisss** [comment]
hi，我是极光的小伙伴。
现在极光也有自己的开发者社区啦。
http://community.jiguang.cn/
以后有比较急的问题，可以试试在社区里「搜索」哦 😊
