### ISSUE TITLE
点击推送的富媒体弹窗类型信息，未显示弹窗

### ISSUE THREAD

**Issue by ljspace** [jpush/jpush-react-plugin#15]
点击推送的富媒体弹窗类型信息，未显示弹窗。只能收到回调中推送的文本内容。
其他几类都可以正常打开：landing page、URL、信息流。

**Comment by KenChoi1992** [comment]
@ljspace 感谢提问，富媒体推送 React 部分貌似没有实现，稍后可能会更新版本。

**Comment by KenChoi1992** [comment]
@ljspace 刚才了解到，富媒体推送客户端貌似没有代码要写，仅仅在res文件中导入富媒体推送的相关资源

**Comment by KenChoi1992** [comment]
@ljspace 没有别的问题就关闭这个 issue 了

**Comment by ljspace** [comment]
@KenChoi1992 你好，我把res文件中的推送相关资源导入，弹窗类型的富媒体推送还是不行。
“landing page、URL、信息流”三类是正常的，可以跳到对应页面或地址。

环境：
react-native 版本 0.28.0
jpush-react-native 版本 0.1.1
android 版本 htc 802d 5.0.2
