### ISSUE TITLE
为什么Android推送的只能接收到Message，接收不到额外加入的键值对

### ISSUE THREAD

**Issue by HouseShine** [jpush/jpush-react-plugin#16]
为什么Android推送的只能接收到Message，接收不到额外加入的键值对

**Comment by KenChoi1992** [comment]
@HouseShine 感谢提问，如果急着用的话可以在 JPushModule 中的 JPushReceiver 的 onReceive（）方法中将 extra 键值对传到 JS

**Comment by KenChoi1992** [comment]
@HouseShine 版本已更新，可以获得 extras。
