### ISSUE TITLE
谢谢官方提供的这个插件

### ISSUE THREAD

**Issue by bang88** [jpush/jpush-react-plugin#2]
看了一下这个插件，感觉要集成非常不方便，如果我是要集成到我现有的项目要怎么做，不是使用这个APP 目录

**Comment by KenChoi1992** [comment]
你自己的项目改造成React Native应用，[参考这个](https://facebook.github.io/react-native/docs/embedded-app-android.html#content)，然后把jpush-sdk放进去，然后参考这个demo，使用NativeModule调用jpush的方法就行了。

**Comment by bang88** [comment]
我的意思是我已经使用react-native 初始化了一个项目了，写了业务逻辑了，怎么集成你这个插件，貌似你这个插件不是一个npm模块，有没有一个集成的流程或者说把它写成一个模块发布到npm上面，我么安装后简单集成一下就好了。

**Comment by KenChoi1992** [comment]
这个是一个React Native应用，目前还没有提供插件的形式使用。。

**Comment by bang88** [comment]
@KenChoi1992 谢谢哈，明白了，目前准备切换到react-native，但是发现推送的没有相关插件，你们有没有计划什么时候推出这个插件，急需官方提供一个插件。

**Comment by KenChoi1992** [comment]
现在还没有JS版的sdk，这个React Native应用也是用的jar包，之后应该会有计划提供。

**Comment by bang88** [comment]
应该会有IOS版本吧？  目前有没有人跟进一下这个模块，项目要用极光推送，没有这个模块搞不了 😢

**Comment by KenChoi1992** [comment]
这个应该是可以做成插件的形式的，我研究一下这个。。

**Comment by bang88** [comment]
嗯 期待，可以用了麻烦 Ping我一下。 我等着用

**Comment by humbass** [comment]
居然有官方的推送，太感动了
