### ISSUE TITLE
按上面配置好后，项目能正常运行，但是接受不到推送

### ISSUE THREAD

**Issue by liz1113012618** [jpush/jpush-react-plugin#20]
"dependencies": {
    "react-native": "^0.20.0",
    "react-native-jpush": "^1.0.8"
  }
上面是我的版本号，完全按上面配置后，请问我发送消息
![b2fd69c2-1927-48a3-80a2-cb6ddd3a801f](https://cloud.githubusercontent.com/assets/18205523/17240772/0cb08404-55a0-11e6-989c-75c867ebf099.png)
请问这是什么原因，难道按上面配置完后还不能发布消息么，或者客户端还需要单独在极光注册么？

**Comment by KenChoi1992** [comment]
@liz1113012618  安装到手机启动应用后，请手动调用一次 JPushModule.initPush()，[详情参考 demo](https://github.com/jpush/jpush-react-plugin/blob/1.1.2/react-native-android/push_activity.js)

**Comment by KenChoi1992** [comment]
@liz1113012618  提了一样的 issue，https://github.com/jpush/jpush-react-plugin/issues/18
因此关掉这个 issue。
