### ISSUE TITLE
配置完成后，发送消息无法接收问题

### ISSUE THREAD

**Issue by liz1113012618** [jpush/jpush-react-plugin#24]
请问 我完全按照ReadMe重新配置好后，现在可以发送推送消息，但是仍然无法接受到消息，而且registrationid也没有
![Uploading 00C91F32-A061-47AE-884B-5FAD20E8E553.png…]()

每次点击GET REGISTRATIONID 后 registrationid都变为null，请问能帮忙看下么 @KenChoi1992

**Comment by liz1113012618** [comment]
static getRegistrationID(cb) {
 		JPushModule.getRegistrationID((id) => {
 			cb(id);
 		});
 	}
getInfo()能正常得到手机端信息，为什么 执行上面这个方法后返回的值为却为“”呢？

**Comment by liz1113012618** [comment]
一开始我以为是权限问题，当我把插件的AndroidManifest.xml完全拷贝到我自己项目的AndroidManifext.xml 里时，第一遍运行能推送成功，当刷新时项目就运行不起来了，提示找不到activity，请问能帮忙看看是什么情况么？谢谢 @

**Comment by KenChoi1992** [comment]
@liz1113012618 不要把插件的 AndroidManifest 拷贝到你的项目下！项目的工程结构如图：

![](https://github.com/KenChoi1992/SomeArticles/blob/master/screenshots/plugin1.png)

完全按照配置是可以收消息的，能否提供报错日志？

**Comment by liz1113012618** [comment]
Android Studio日志

08-01 21:44:01.957 2184-2184/com.hellow I/art: Late-enabling -Xcheck:jni
08-01 21:44:02.065 2184-2204/com.hellow D/OpenGLRenderer: Render dirty regions requested: true
                                                          
                                                          [ 08-01 21:44:02.077  2184: 2184 D/         ]
                                                          HostConnection::get() New Host Connection established 0xeb87a240, tid 2184
08-01 21:44:02.088 2184-2184/com.hellow D/Atlas: Validating map...
08-01 21:44:02.120 2184-2204/com.hellow D/libEGL: loaded /system/lib/egl/libEGL_emulation.so
08-01 21:44:02.120 2184-2204/com.hellow D/libEGL: loaded /system/lib/egl/libGLESv1_CM_emulation.so
08-01 21:44:02.124 2184-2204/com.hellow D/libEGL: loaded /system/lib/egl/libGLESv2_emulation.so
                                                  
                                                  [ 08-01 21:44:02.130  2184: 2204 D/         ]
                                                  HostConnection::get() New Host Connection established 0xe2516120, tid 2204
08-01 21:44:02.160 2184-2204/com.hellow I/OpenGLRenderer: Initialized EGL, version 1.4
08-01 21:44:02.191 2184-2204/com.hellow D/OpenGLRenderer: Enabling debug mode 0
08-01 21:44:02.219 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:44:02.219 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe2519200, error=EGL_SUCCESS
08-01 21:44:02.313 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:44:02.314 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe2519220, error=EGL_SUCCESS
08-01 21:44:02.327 2184-2184/com.hellow W/unknown:React: Unable to dispatch keyboard events in JS as the react instance has not been attached
08-01 21:44:02.991 2184-2214/com.hellow I/art: Thread[19,tid=2214,WaitingForJniOnLoad,Thread*=0xed22b400,peer=0x12c63520,"AsyncTask #1"] recursive attempt to load library "/data/app/com.hellow-1/lib/x86/libreactnativejni.so"
08-01 21:44:03.003 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTRenderableViewManager
08-01 21:44:03.004 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
08-01 21:44:03.008 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
08-01 21:44:03.009 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
08-01 21:44:03.010 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
08-01 21:44:03.016 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
08-01 21:44:03.018 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
08-01 21:44:03.047 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
08-01 21:44:03.049 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
08-01 21:44:03.055 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
08-01 21:44:03.055 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
08-01 21:44:03.059 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
08-01 21:44:03.064 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
08-01 21:44:03.066 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
08-01 21:44:03.067 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
08-01 21:44:03.071 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
08-01 21:44:03.074 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
08-01 21:44:03.076 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
08-01 21:44:03.085 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
08-01 21:44:03.085 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageViewManager
08-01 21:44:03.086 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextInlineImageShadowNode
08-01 21:44:03.087 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
08-01 21:44:03.094 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
08-01 21:44:03.095 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
08-01 21:44:03.096 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.toolbar.ReactToolbarManager
08-01 21:44:03.105 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
08-01 21:44:03.117 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
08-01 21:44:03.126 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
08-01 21:44:03.127 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.webview.ReactWebViewManager
08-01 21:44:03.147 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.recyclerview.RecyclerViewBackedScrollViewManager
08-01 21:44:03.159 2184-2199/com.hellow W/art: Suspending all threads took: 10.067ms
08-01 21:44:03.161 2184-2214/com.hellow W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
08-01 21:44:03.315 2184-2199/com.hellow I/art: Background sticky concurrent mark sweep GC freed 1702(68KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 1998KB/1998KB, paused 5.183ms total 46.698ms
08-01 21:44:03.660 2184-2222/com.hellow I/ReactNativeJS: Running application "Hellow" with appParams: {"initialProps":{},"rootTag":1}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
08-01 21:44:03.755 2184-2223/com.hellow W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init
08-01 21:44:03.763 2184-2223/com.hellow W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init
08-01 21:44:03.764 2184-2223/com.hellow W/JPush: [SharePreferenceProcess] context is null, in SharePreferenceProcess.init
08-01 21:44:03.931 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:44:03.931 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe390e600, error=EGL_SUCCESS
08-01 21:44:04.230 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:44:04.230 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe390e600, error=EGL_SUCCESS
08-01 21:47:40.286 2184-2204/com.hellow D/OpenGLRenderer: endAllStagingAnimators on 0xe0420600 (RippleDrawable) with handle 0xeb8ad280
08-01 21:47:46.229 2184-2223/com.hellow I/JPushModule: init Success!
08-01 21:47:46.241 2184-2184/com.hellow W/JPush: [AndroidUtil] AndroidManifest.xml missing intent filter for DaemonService: cn.jpush.android.intent.DaemonService
08-01 21:47:46.242 2184-2184/com.hellow E/JPush: [AndroidUtil] AndroidManifest.xml missing required intent filter for PushReceiver: cn.jpush.android.intent.NOTIFICATION_RECEIVED_PROXY
08-01 21:47:46.242 2184-2184/com.hellow W/JPush: [AndroidUtil] You should make main activity extends InstrumentedActivity (JPush), otherwise you will not see user click and user active time start on report in Portal. 
08-01 21:47:46.242 2184-2184/com.hellow W/JPush: [PushService] JPush running checked failed!
08-01 21:47:46.277 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:47:46.277 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe39b4f00, error=EGL_SUCCESS
08-01 21:47:46.305 2184-2204/com.hellow V/RenderScript: 0xe1726400 Launching thread(s), CPUs 4
08-01 21:47:47.711 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:47:47.711 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe390f140, error=EGL_SUCCESS
08-01 21:47:49.428 2184-2204/com.hellow D/OpenGLRenderer: endAllStagingAnimators on 0xe0425d80 (RippleDrawable) with handle 0xe1754050
08-01 21:47:50.307 2184-2204/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:47:50.307 2184-2204/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe390f320, error=EGL_SUCCESS
08-01 21:47:51.879 2184-2204/com.hellow D/OpenGLRenderer: endAllStagingAnimators on 0xe04bcb00 (RippleDrawable) with handle 0xe042a3b0

**Comment by liz1113012618** [comment]
08-01 21:57:08.952 10078-10164/com.hellow I/JPushModule: init Success!
08-01 21:57:09.255 10078-10164/com.hellow I/JPushModule: init Success!
08-01 21:57:09.501 10078-10164/com.hellow I/JPushModule: init Success!
08-01 21:57:10.208 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:10.208 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe1785c80, error=EGL_SUCCESS
08-01 21:57:10.316 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:10.316 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xef619280, error=EGL_SUCCESS
08-01 21:57:10.482 10078-10078/com.hellow W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
08-01 21:57:11.266 10078-10163/com.hellow I/ReactNativeJS: Resume push press
08-01 21:57:11.268 10078-10164/com.hellow I/JPushModule: Resume push
08-01 21:57:11.519 10078-10163/com.hellow I/ReactNativeJS: Resume push press
08-01 21:57:11.521 10078-10164/com.hellow I/JPushModule: Resume push
08-01 21:57:12.209 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:12.209 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe1785c80, error=EGL_SUCCESS
08-01 21:57:14.225 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:14.225 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe1785c80, error=EGL_SUCCESS
08-01 21:57:16.227 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:16.227 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe1785c80, error=EGL_SUCCESS
08-01 21:57:16.516 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:16.516 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe3a5e980, error=EGL_SUCCESS
08-01 21:57:18.225 10078-10136/com.hellow W/EGL_emulation: eglSurfaceAttrib not implemented
08-01 21:57:18.225 10078-10136/com.hellow W/OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0xe1785c80, error=EGL_SUCCESS
08-01 21:57:18.929 10078-10136/com.hellow D/OpenGLRenderer: endAllStagingAnimators on 0xe17cd380 (RippleDrawable) with handle 0xef6f2830

**Comment by KenChoi1992** [comment]
@liz1113012618 你看到你的日志没有：
```
/JPush: [AndroidUtil] AndroidManifest.xml missing intent filter for DaemonService: cn.jpush.android.intent.DaemonService
08-01 21:47:46.242 2184-2184/com.hellow E/JPush: [AndroidUtil] AndroidManifest.xml missing required intent filter for PushReceiver: cn.jpush.android.intent.NOTIFICATION_RECEIVED_PROXY
08-01 21:47:46.242 2184-2184/com.hellow W/JPush: [AndroidUtil] You should make main activity extends InstrumentedActivity (JPush), otherwise you will not see user click and user active time start on report in Portal. 
08-01 21:47:46.242 2184-2184/com.hellow W/JPush: [PushService] JPush running checked failed!
```
你肯定改了 jpush-react-native 的 AndroidManifest，你 install 完这个插件后根本并不需要动插件的AndroidManifest 代码，仅仅要动插件的 build.gradle 和你自己的 module 的 build.gradle、settings.gradle，我已经说的很清楚了。

**Comment by liz1113012618** [comment]
问题已经解决了，原来是我把我自己项目
    @KenChoi1992  ![image](https://cloud.githubusercontent.com/assets/18205523/17319227/d6337068-58be-11e6-999d-6de73e9d33bb.png)的版本号从1.3.1改成了1.2.0，导致SDK有些功能用不了，谢谢你们啊，一直不厌其烦的帮我解答，真是太给力

**Comment by KenChoi1992** [comment]
@liz1113012618 ReadMe 中有写要改平台版本号。。既然解决了我就关掉 issue 了。
