### ISSUE TITLE
iOS下在推送时设置了角标，如何实现点击通知后角标消减？

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-plugin#25]
例如在推送时选择badge +1, 那么点击通知之后，如何实现badge -1 ?
好像在文档中没有找到getBadge等类似方法？

**Comment by huangminlinux** [comment]
在 appDelegate.m 文件里面 添加。如下代码

- (void)applicationDidEnterBackground:(UIApplication *)application {
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0];      //0 设置为0 ，可以设置为任意的值
}

**Comment by pampang** [comment]
能够有类似getBadge的方法，可以获取到当前的badge数吗？
