### ISSUE TITLE
Apikey的配置能不能提到其他地方去

### ISSUE THREAD

**Issue by charleyw** [jpush/jpush-react-plugin#26]
现在的Apikey的配置是在 jpush-react-plugin 的build.gradle文件里面，
但是这个文件 是在 **node_modules** 目录里面的，显然是不在git里面的。

如果有多个人开发这个同一个项目的话，那他把项目clone到本地之后，还需要手动去修改这些东西，才能生效。如果他忘记了，或者不知道的还，那不就坑爹了。

建议把这个东西 弄到 MainActivity 里面去。

**Comment by KenChoi1992** [comment]
@charleyw 更新了版本以及 ReadMe，可以自动配置 AppKey
