### ISSUE TITLE
能更新一下文档不

### ISSUE THREAD

**Issue by charleyw** [jpush/jpush-react-plugin#27]
虽然你们是官方维护的jpush，但是文档跟 reactnativecn的那个比真的差挺远的。不过貌似你们用的API比较新。

用react native的大部分都是前端程序员（说的就是我），一些涉及到原生应用的配置，看着都很头疼，有时候会被一些原生应用的基本概念挡在门外。

能花点时间整理一下文档不，尽可能写详细一点。

**Comment by KenChoi1992** [comment]
@charleyw 文档更新了，可以用脚本来进行配置了，具体看 ReadMe
