### ISSUE TITLE
请问如何设置版本号

### ISSUE THREAD

**Issue by liz1113012618** [jpush/jpush-react-plugin#29]
我的项目是以前下载，如果在Android5.0真机运行需要把
dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
1.3.1 => 1.2.0 不然是运行不起来的，但是加了jpush插件后，一开始我没改版本号（1.3.1）在模拟器上运行一切正常，但是当我要到真机运行时，并把版本号换成(1.2.0),项目能正常运行，但是发送通知后接受不到RegistrationId,也接受不到推送消息，请问这是什么原因啊？ @

**Comment by liz1113012618** [comment]
貌似就认1.3.1这个版本号

**Comment by KenChoi1992** [comment]
@liz1113012618 现在版本号早就2.0往上了，你试试更新下版本吧，我现在用的是 2.1.0

**Comment by KenChoi1992** [comment]
@liz1113012618 没什么问题的话，我就关了
