### ISSUE TITLE
建议详细书写配置文档

### ISSUE THREAD

**Issue by zhenlovezhen2012** [jpush/jpush-react-plugin#3]
使用react的绝大部分是不懂ios或安卓的，我觉得您应该脱离jush文档，自己重新详细定义一份文档。

到底哪些必须配置，哪些不用配置，而不是一个链接；

仅是建议，望参考。

**Comment by KenChoi1992** [comment]
怎么说？这本来就是React Native版本的jpush。只不过能在React Native中使用jpush而已，谈不上脱离jpush文档，所用的接口还是jpush-sdk提供的，只不过能在JS中直接调用而已。而且，你说的配置文档，链接提供的不够完善是么，那么有哪里不理解呢？

**Comment by zhenlovezhen2012** [comment]
感谢回复，我先试试，在请教您
