### ISSUE TITLE
安卓推送问题

### ISSUE THREAD

**Issue by jerry81333** [jpush/jpush-react-plugin#30]
安卓按文档配置后，能拿到注册ID，推送后台也显示推送成功，但是手机端消息接受不到，后台目标|成功一直是1|0，还一直有推送提示，“Jpush提示：缺少统计代码 检测到集成SDK未添加统计代码”。

**Comment by KenChoi1992** [comment]
@jerry81333 起来的时候要调用一下 initJPush() 方法，在 MainActivity 的生命周期函数调用 JPushInterface.resume() 和 JPushInterface.stop() 可以去掉提示。 [参考文档：](http://docs.jiguang.cn/client/android_api/)

**Comment by jerry81333** [comment]
@KenChoi1992 调用了 initJPush()，不然get注册ID都出不来，但是即使出来了，后台也有目标数了，后台推送也能推送，但是手机上没有任何推送消息，后台成功数也依旧为0。

**Comment by KenChoi1992** [comment]
@jerry81333 关于推送的问题可以在[我们的社区](http://community.jiguang.cn/)提问，我们有专门的技术支持负责，这里是关于插件的使用问题或者 bug 反馈。
