### ISSUE TITLE
请问iOS推送角标怎么设置

### ISSUE THREAD

**Issue by liz1113012618** [jpush/jpush-react-plugin#31]
运行项目后角标一直是1，不管推送多少条都没有变化；当我在AppDelegate.m添加了
-(void)applicationDidEnterBackground:(UIApplication *)application {
  
  [[UIApplication sharedApplication] setApplicationIconBadgeNumber:0]; //0 设置为0 ，可以设置为任意的值
}
方法后，还是没有实现：每推送一下消息角标加一，每点击一下图标，角标减一的效果。
请问这个效果在ios怎么实现？ @

**Comment by huangminlinux** [comment]
角标加一，需要服务端来实现，我们 jpush接口支持加一的操作，需要在推送参数 badge 设为 +1 ,  而打开应用减一可以,通过[[UIApplication sharedApplication] setApplicationIconBadgeNumber: [UIApplication sharedApplication].applicationIconBadgeNumber -1]; 来设置，


有一点需要注意的是，极光控制台会维护一个badge 这个角标，应该尽量保持服务端的badge 和 手机端的badge 同步。   jpush-react-plugin, 提供 setbadge 的接口

**Comment by liz1113012618** [comment]
请问怎么保持服务端的badge和手机端的badge同步呢？换句话就是setbadge该怎么用啊
