### ISSUE TITLE
请问怎么保持服务器端badge和移动端角标一致呢？

### ISSUE THREAD

**Issue by liz1113012618** [jpush/jpush-react-plugin#32]
推送几条消息后经常发现服务器端发出的消息和手机端角标经常对应不起来，不知道怎么实现服务器端badge和手机端角标保持一致？能详细说明下么？

**Comment by huangminlinux** [comment]
jpush-react-plugin 有个方法。     static setBadge(badge, cb){
     	JPushModule.setBadge(badge, (value) => {
     		cb(value);
     	});
     } 

这个方法是设置服务端的badge 这个值的

**Comment by liz1113012618** [comment]
能讲下具体怎么实现吗？对原生不是很熟，不知道怎么在.js中获取移动端的角标。能给下具体代码就更好了 @huangminlinux

**Comment by huangminlinux** [comment]
我再写几个常用接口吧，好了到时候通知你，

**Comment by liz1113012618** [comment]
直接调JPushModule.setBadge(0,(value)=>this.BadgeValue(value)); 发现并没有同步服务器啊，前面那个number类型数什么意思啊？而且我希望直接点击应用角标不变，只有点击推送的消息后角标才会减1，请问怎么设置啊？

**Comment by huangminlinux** [comment]
点击推送会 进入一个回调函数，  这个readme 上有说明，   我直接复制给你吧


为了在收到推送点击进入应用能够获取该条推送内容需要在 AppDelegate.m didReceiveRemoteNotification 方法里面添加 [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo] 方法，注意：这里需要在两个方法里面加一个是iOS7以前的一个是iOS7即以后的，如果AppDelegate.m 没有这个两个方法则直接复制这两个方法；如下所示
- (void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo {
  // 取得 APNs 标准信息内容

  [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}
//iOS 7 Remote Notification
- (void)application:(UIApplication *)application didReceiveRemoteNotification:  (NSDictionary *)userInfo fetchCompletionHandler:(void (^)   (UIBackgroundFetchResult))completionHandler {

  [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
}


你需要  在 js 里面监听 kJPFDidReceiveRemoteNotification 事件
