### ISSUE TITLE
getRegistrationID方法在模拟器上会报错

### ISSUE THREAD

**Issue by viix** [jpush/jpush-react-plugin#33]
是否应该加上些error机制
![simulator screen shot aug 9 2016 8 52 07 pm](https://cloud.githubusercontent.com/assets/8758499/17516807/28b68898-5e73-11e6-8a65-fa0a1b9ce26c.png)

**Comment by kiliwalk** [comment]
我也碰到了. 为了方便后面的人检索, 我把详细错误信息贴出来. 
ios模拟器上使用时, 如果调用`JPushModule.getRegistrationID`方法会报如下异常:
```
index.ios.bundle:23970Exception '*** -[__NSPlaceholderArray initWithObjects:count:]: 
attempt to insert nil object from objects[0]' was thrown 
while invoking getRegistrationID on target RCTJPushModule with params (
    39
)
```

**Comment by huangminlinux** [comment]
可以试试1.1.6版本
