### ISSUE TITLE
统计API

### ISSUE THREAD

**Issue by viix** [jpush/jpush-react-plugin#35]
/**
     * rn 0.29.0 以下版本,请使用此方法,并去掉 MainApplication 文件, 0.29.0 以上版本请去掉这些注释代码
     * 注意改变其中的 JSMainModuleName 的路径(因为此版本适配了 rn 0.30.0, index.android.js 放在了项目目录下)
     * 相应地,index.android.js 中 push_activity.js,set_activity.js的引用路径也要改变(参考 index.android.js)
     */
//    private ReactRootView mReactRootView;
//    private ReactInstanceManager mReactInstanceManager;
//    private boolean SHUTDOWN_TOAST = false;
//    private boolean SHUTDOWN_LOG = false;

//    @Override
//    protected void onCreate(Bundle savedInstanceState) {
//        super.onCreate(savedInstanceState);
//        mReactRootView = new ReactRootView(this);
//        mReactInstanceManager = ReactInstanceManager.builder()
//                .setApplication(getApplication())
//                .setBundleAssetName("index.android.bundle")
//                .setJSMainModuleName("react-native-android/index.android")
//                .addPackage(new MainReactPackage())
//                .addPackage(new JPushPackage(SHUTDOWN_TOAST, SHUTDOWN_LOG))
//                .setUseDeveloperSupport(BuildConfig.DEBUG)
//                .setInitialLifecycleState(LifecycleState.RESUMED)
//                .build();
//        mReactRootView.startReactApplication(mReactInstanceManager, "PushDemoApp", null);
//
//        setContentView(mReactRootView);
//    }

这里的意思是如果>0.30，uncomment掉这段代码？setJSMainModuleName应该设置自己项目的index？

**Comment by viix** [comment]
@KenChoi1992 可以帮忙看下么

**Comment by KenChoi1992** [comment]
@viix <0.29 要用这段代码，否则去掉，用 MainApplication 来启动。setJSMainModuleName 要指向 index.android.js 所在的路径。

**Comment by viix** [comment]
@KenChoi1992 got it thanks
