### ISSUE TITLE
这个repo是demo工程吧, 请问npm包对应的repo有吗?

### ISSUE THREAD

**Issue by kiliwalk** [jpush/jpush-react-plugin#37]
是不是也可以把npm包对应的repo放到github上啊, 这样可以接受社区各种PRs改进

**Comment by KenChoi1992** [comment]
@kiliwalk npm 包对应的 repository 在这个地址 https://github.com/KenChoi1992/react-native-jpush-plugin

**Comment by kiliwalk** [comment]
@KenChoi1992 谢谢
