### ISSUE TITLE
Android下会有提示: Init push success

### ISSUE THREAD

**Issue by kiliwalk** [jpush/jpush-react-plugin#38]
调用initPush后, 会有这个toast提示, 是不是可以注释掉呢? 或者加个选项?

**Comment by KenChoi1992** [comment]
@kiliwalk 在初始化 JPushPackage时，将 SHUTDOWN_TOAST, SHUTDOWN_LOG设置为 true 即可

**Comment by kiliwalk** [comment]
@KenChoi1992 好的, 谢谢. 这两个参数是不是默认false较好? 另外是不是可以放到js层去设置?

**Comment by KenChoi1992** [comment]
@kiliwalk  这两个参数默认就是 false，初始化 JPushPackage 是必要的，倒是可以提供接口给 js 侧，让 js 侧可以控制。

**Comment by KenChoi1992** [comment]
@kiliwalk 没什么问题的话，就关闭issue了
