### ISSUE TITLE
[Android]请教一个问题关于通知唤醒

### ISSUE THREAD

**Issue by Lepinr** [jpush/jpush-react-plugin#43]
在应用退出后，点击通知可以打开应用，但是通知的参数应该怎样传递进入RN呢？

**Comment by Lepinr** [comment]
@KenChoi1992 help me : )

**Comment by KenChoi1992** [comment]
传入RN是指传到JS？ 在点击通知的时候会执行 onReceive中点开通知的方法，在这个方法中通过 RCTDeviceEventEmitter 调用了 JSModule 中的 openNotification 方法。你可以参考一下 push_activity.js

**Comment by Lepinr** [comment]
@KenChoi1992 谢谢回复

我的意思是通过 "点击通知冷启动应用" 怎么获得通知参数.

**Comment by KenChoi1992** [comment]
@Lepinr openNotification 传了一个 WritableMap 进去，通过 map 可以得到 alertContent, extras 等内容。你可以看看 JPushModule 中 onReceive() 方法。

**Comment by Lepinr** [comment]
@KenChoi1992  thank you.
