### ISSUE TITLE
Cannot read property 'setAlias' of undefined

### ISSUE THREAD

**Issue by RocWangv** [jpush/jpush-react-plugin#48]
首先，感谢提供这个组件！！！

- IOS模拟器，在调用setAlias时出错，代码如下：

   

> import JPushModule from 'jpush-react-native';
    .........  //其他代码
> JPushModule.setAlias('283', ()=> {
                        console.log('-------success---------');
                    }, ()=> {
                        console.log('-------fail---------');
                    });

- 错误描述：Cannot read property 'setAlias' of undefined

- 版本信息：

> "react": "15.2.1",
    "react-native": "0.31.0",
    "jpush-react-native": "^1.1.3",

**Comment by huangminlinux** [comment]
使用该推送插件，需要在真机下使用

**Comment by RocWangv** [comment]
请问setAlias 在真机下是兼容ios和android的吗

**Comment by huangminlinux** [comment]
是的
