### ISSUE TITLE
请问这个和jpush-react-native-plugin应该用哪个？

### ISSUE THREAD

**Issue by HADB** [jpush/jpush-react-plugin#5]
@KenChoi1992  我之前有关注到你的另一个项目 https://github.com/KenChoi1992/react-native-jpush-plugin 我看到你最近也在更新另一个项目，请问这两个我应该用哪一个？他们有什么差别？

**Comment by KenChoi1992** [comment]
@HADB 应该使用这个，这个是官方命名的，之前那个是我在npm上面测试而创建的，基本上只维护这个项目了。
