### ISSUE TITLE
IOS点击通知不触发事件？

### ISSUE THREAD

**Issue by liuhuapiaoyuan** [jpush/jpush-react-plugin#51]
NativeAppEventEmitter.addListener(
  'ReceiveNotification',
  (notification) => console.log(notification)
);

这段代码无效果
已经添加了

为了在收到推送点击进入应用能够获取该条推送内容需要在 AppDelegate.m didReceiveRemoteNotification 方法里面添加 [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo] 方法

**Comment by huangminlinux** [comment]
你好你的系统是  iOS10 吗？

**Comment by huangminlinux** [comment]
iOS10 的话需要添加 如下代码
- (void)jpushNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler: (void (^)())completionHandler {
  // Required
  NSDictionary * userInfo = response.notification.request.content.userInfo;
  [[NSNotificationCenter defaultCenter] postNotificationName:kJPFDidReceiveRemoteNotification object:userInfo];
  if([response.notification.request.trigger isKindOfClass:[UNPushNotificationTrigger class]]) {
    [JPUSHService handleRemoteNotification:userInfo];
  }
  else {
    // 本地通知
  }
  completionHandler();  // 系统要求执行这个方法
}


同样在appdelegete.m 里面添加
