### ISSUE TITLE
JPUSHService registerForRemoteNotificationTypes

### ISSUE THREAD

**Issue by devhyunjae** [jpush/jpush-react-plugin#53]
Hi,

I want to show the `disallow allow push notification dialog` more later than app launches(didFinishLaunchingWithOptions).

In here, the document recommended to call that method in didFinishLaunchingWithOptions callback.

But can i call this when i want? Is there a javascript exported method?

I have analysed some of your lib code, and found that,

`jpush-react-native/ios/RCTJPushModule/RCTJPushModule/RCTJPushModule.m`

`LIne #59`

```
//RCT_EXPORT_METHOD(setupPush:(NSString *)name) {
//  if ([[UIDevice currentDevice].systemVersion floatValue] >= 8.0) {
//    //可以添加自定义categories
//    [JPUSHService registerForRemoteNotificationTypes:(UIUserNotificationTypeBadge |
//                                                      UIUserNotificationTypeSound |
//                                                      UIUserNotificationTypeAlert)
//                                          categories:nil];
//  } else {
//    //categories 必须为nil
//    [JPUSHService registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge |
//                                                      UIRemoteNotificationTypeSound |
//                                                      UIRemoteNotificationTypeAlert)
//                                          categories:nil];
//  }
//
//  [JPUSHService setupWithOption:nil appKey:appKey
//                        channel:channel apsForProduction:isProduction];
//}
```

this code is commented.

Can i uncomment this, and use this method? Is there a side-effect that I have to concern?

**Comment by huangminlinux** [comment]
Yes！ You can call this when you need it.  But this is rare.   Because after call this code，you can receive, If you do not want to receive the push can be controlled through the server

so you question ：
1. can i call this when i want? Is there a javascript exported method?   
        yes

2. Can i uncomment this, and use this method?    yes ，But you should adapt ios10

3.  Is there a side-effect that I have to concern?    I recommend that push control should be put on the server side

**Comment by devhyunjae** [comment]
Thanks, I'll close the issue

**Comment by flavordaaave** [comment]
Seems there is `setupPush` method now which takes care of that.
But in your docs you mention to add following code to the `AppDelegate.m`:
```
  if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
  #ifdef NSFoundationVersionNumber_iOS_9_x_Max
      JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
      entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
      [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
    
  #endif
  } else if ([[UIDevice currentDevice].systemVersion floatValue] >= 8.0) {
    [JPUSHService registerForRemoteNotificationTypes:(UIUserNotificationTypeBadge |
                                                      UIUserNotificationTypeSound |
                                                      UIUserNotificationTypeAlert)
                                          categories:nil];
  } else {
    [JPUSHService registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge |
                                                      UIRemoteNotificationTypeSound |
                                                      UIRemoteNotificationTypeAlert)
                                          categories:nil];
  }
```
but in the `setupPush` the part
```
  if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
  #ifdef NSFoundationVersionNumber_iOS_9_x_Max
      JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
      entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
      [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
    
  #endif
```

Is this something important? If yes, this should be added to `setupPush` method.

**Comment by flavordaaave** [comment]
@huangminlinux I noticed when calling `setupPush` at a later point (and not having the `registerForRemoteNotificationConfig` and `registerForRemoteNotificationTypes` in the `AppDelegate.m`, in JS code, `addReceiveOpenNotificationListener` is NEVER called but always just `addReceiveNotificationListener`.

I really do NOT want to ask the user for push permissions directly on app launch since we first want to explain the user why we need those permissions. But currently, when asking later (calling `setupPush` at a later point) does NOT seem to work. Am I missing something?

**Comment by huangminlinux** [comment]
@fanglufanglu setupPush function do not update to iOS 10 now， we will fix it in next version.

**Comment by huangminlinux** [comment]
@fanglufanglu ,you can update to 2.0.8 version.

**Comment by flavordaaave** [comment]
@huangminlinux THX, I just tested version `2.0.8`but still the listener I created with `addReceiveOpenNotificationListener` is NEVER called on iOS (iOS 11 beta). When the app is opened by a push notification the listener for `addReceiveNotificationListener` instead...

**Comment by huangminlinux** [comment]
If you app is not open yet, click notification to launch app will callback in [addOpenNotificationLaunchAppListener](https://github.com/jpush/jpush-react-native/blob/master/example/documents/iOS_API.md)

**Comment by flavordaaave** [comment]
Yes, that is the intended behavior. But this is ONLY working if I have the following code in my AppDelegate.m
```
  if ([[UIDevice currentDevice].systemVersion floatValue] >= 10.0) {
  #ifdef NSFoundationVersionNumber_iOS_9_x_Max
    JPUSHRegisterEntity * entity = [[JPUSHRegisterEntity alloc] init];
    entity.types = UNAuthorizationOptionAlert|UNAuthorizationOptionBadge|UNAuthorizationOptionSound;
    [JPUSHService registerForRemoteNotificationConfig:entity delegate:self];
  #endif
  } else if ([[UIDevice currentDevice].systemVersion floatValue] >= 8.0) {
    [JPUSHService registerForRemoteNotificationTypes:(UIUserNotificationTypeBadge |
                                                      UIUserNotificationTypeSound |
                                                      UIUserNotificationTypeAlert)
                                          categories:nil];
  } else {
    [JPUSHService registerForRemoteNotificationTypes:(UIRemoteNotificationTypeBadge |
                                                      UIRemoteNotificationTypeSound |
                                                      UIRemoteNotificationTypeAlert)
                                          categories:nil];
  }
```

If I remove this code and use `setupPush` method somewhere later in my app, the `addOpenNotificationLaunchAppListener` is NEVER called.

**Comment by huangminlinux** [comment]
I test it with [demo](https://github.com/jpush/jpush-react-native/tree/master/example), and it is no problem. You can refer to this [demo](https://github.com/jpush/jpush-react-native/tree/master/example)。
