### ISSUE TITLE
如何实现当点击通知的时候，切换后台已存在的应用到前台展示？

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-plugin#6]
如何实现当点击通知的时候，切换后台已存在的应用到前台展示？

**Comment by KenChoi1992** [comment]
之前的版本有bug，在点击通知的时候无法跳转，现已修复，可以重新拉取一下代码。

**Comment by cuitianze** [comment]
@KenChoi1992 安卓下点击消息依旧不能打开APP， 这个问题已经解决了吗, 盼回复。
另一个插件react-native-jpush也存在这样的问题，判断应用是否在前台的逻辑有问题。
[判断App位于前台或者后台的6种方法] https://github.com/wenmingvs/AndroidProcess

**Comment by KenChoi1992** [comment]
这个问题新版本已经解决了啊，你用的是什么版本的？

**Comment by cuitianze** [comment]
v0.0.11 能加您一个联系方式吗？
我可是极光推送的会员哦~~~~~ 
github上的commit，没有看到对应用是否在前台的fix。

**Comment by KenChoi1992** [comment]
是这样，我没有在点击通知的时候判断是否在前台，而是说在收到点击通知的事件时，就跳转到应用的启动 Activity，相关代码可以参考 JPushModule 类中收到点击通知的相关事件。你可以调试一下，看看点击通知以后有没有执行到这里，如果确实是 bug，那我再打开这个 issue。

**Comment by cuitianze** [comment]
用户点击打开了通知--打印出

_正在打开应用--未打印出_

```
                Log.d(TAG, "用户点击打开了通知");
                WritableMap map = Arguments.fromBundle(bundle);
                mRAC.getJSModule(DeviceEventManagerModule.RCTDeviceEventEmitter.class)
                        .emit("openNotification", map);
                if (mModule != null && mModule.mContext != null) {
                    Intent intent = new Intent(context, mModule.mContext.getClass());
                    intent.putExtras(bundle);
                    intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                    context.startActivity(intent);
                    Log.d(TAG, "正在打开应用");
                }
```
这里的if判断可能存在问题，

我注释掉这里的if判断，报了如下的错：

**Comment by KenChoi1992** [comment]
@cuitianze 这里调试一下，看看mModule.mContext是否为null，实际上如果应用退到后台的话，是不会为null的

**Comment by ljspace** [comment]
@KenChoi1992 你好，我这边也碰到前后台切换问题，不知道什么原因。
react-native 端 `addReceiveOpenNotificationListener` 监听有收到回调，但是后台应用没有切换到前台。
`jpush-react-native` 插件版本：0.1.0
android 版本：4.1.1（模拟器）
react-native 版本：0.28.0
