### ISSUE TITLE
程序关闭后不能实现自启动

### ISSUE THREAD

**Issue by songyu719** [jpush/jpush-react-plugin#7]
已经在安装中心设置了自启动省电管理也让APP不被清除了 然而 推送服务依然不能自启

**Comment by KenChoi1992** [comment]
@songyu719 Android还是iOS？

**Comment by songyu719** [comment]
Android 程序一关闭 就收不到推送了 但是再打开 APP就可以收到！

在 2016-07-04 11:18:30，"KenChoi1992" <notifications@github.com> 写道：


@songyu719 Android还是iOS？

**Comment by songyu719** [comment]
@KenChoi1992  这个帖子也并没有给出解决方案啊！我的测试机是魅蓝metal 我设置了自启 然而还是启动不了！

**Comment by KenChoi1992** [comment]
@songyu719 这个问题，我们会在别的手机再测试一下，看看是不是 push 的问题

**Comment by liuxisong** [comment]
@KenChoi1992 @songyu719    遇到同样的问题，应用退出就收不到推送了

**Comment by ljspace** [comment]
@KenChoi1992  也遇到这个问题，应用退出收不到推送了。希望能尽快修复

**Comment by KenChoi1992** [comment]
@liuxisong  @ljspace 应用在后台运行不能收到推送吗？

**Comment by ljspace** [comment]
@KenChoi1992 应用在后台运行可以正常收到推送，应用退出了就收不到推送了。

**Comment by KenChoi1992** [comment]
@ljspace 稍后再更新一下 jpush-sdk 的版本，看看能否解决这个问题

**Comment by liuxisong** [comment]
@KenChoi1992  我试过华为和魅族，这两款都是应用退出后收不到推送，其他机型没有试

**Comment by KenChoi1992** [comment]
@liuxisong 这周发个新版本，最迟周末，把这几个 issue 都修复一下。。

**Comment by liuxisong** [comment]
@KenChoi1992   非常感谢！

**Comment by KenChoi1992** [comment]
@liuxisong 被杀进程了是不能收到推送的，除非有其他集成了jpush的进程没有被杀掉，这样可以被拉起。
