### ISSUE TITLE
界面切换导致收不到推送

### ISSUE THREAD

**Issue by songyu719** [jpush/jpush-react-plugin#8]
我的APP Home页可以收到推送 一但切换到另外一个页面就会收不到推送了 只有重启APP才能收到之前的推送消息

**Comment by KenChoi1992** [comment]
@songyu719 是这样，你是否在启动 Activity 调用了 JPushInterface.init() 呢？

**Comment by KenChoi1992** [comment]
@songyu719 我这边测试切换界面是可以收到推送的，如果没有跟进的话，我就关掉这个 issue 了
