### ISSUE TITLE
【ios下无法接收到推送消息】配置成功，deviceToken已经成功推上服务器，推送页面也能正常检测到设备

### ISSUE THREAD

**Issue by pampang** [jpush/jpush-react-plugin#9]
【ios下无法接收到推送消息】配置成功，deviceToken已经成功推上服务器，推送页面也能正常检测到设备。
请问这可能是什么原因导致的呢？

设备：
ipod touch
ios v8.4

**Comment by huangminlinux** [comment]
你的推送证书配置成功没？，推送的环境选对了吗？

**Comment by pampang** [comment]
问题已经解决，感谢~

**Comment by bluerunrun** [comment]
@pampang 你好，请问最后你是怎么解决了的呢？ 我现在也是iOS 下，配置成功，deviceToken也上传成功，JPUSH 也注册成功了，iOS 上还是没法接收到推送 。我重新弄一个react-native 工程，用同样的证书，同样的 appkey，却可以推送成功。实在是没有办法了。

**Comment by pampang** [comment]
@bluerunrun 可以多装几次app试试，我卸载了重装就好了。同时要注意推送选择的模式。
